import AxeBuilder from "@axe-core/playwright"
import { scrollFacilityIntoView, chooseFacilityStillImage } from "../support/facility-viewer"
import { expect, test } from "@playwright/test"

test.describe("facility inspection", () => {
  test("adaptive automatic loading preserves assessment quantities", async ({ page }) => {
    await page.addInitScript(() => { window.__GN_FACILITY_DIAGNOSTICS__ = true })
    await page.goto("/")
    const inspector = page.getByTestId("facility-inspection")
    await scrollFacilityIntoView(inspector)
    await expect(inspector).toHaveAttribute("data-phase", "ready")
    const caption = await inspector.getByTestId("facility-assessment-caption").textContent()
    for (const name of ["Power", "Cooling", "Storage", "Workloads"]) {
      await inspector.getByRole("button", { name, exact: false }).filter({ hasText: name }).click()
      await expect(inspector.getByTestId("facility-assessment-caption")).toHaveText(caption!)
    }
    const canvas = inspector.locator("canvas")
    expect(await canvas.evaluate((element: HTMLCanvasElement) => element.__gnFacilitySnapshot!().drawCalls)).toBeLessThanOrEqual(40)
    expect(await canvas.evaluate((element: HTMLCanvasElement) => element.__gnFacilitySnapshot!().triangles)).toBeLessThanOrEqual(60_000)
    await inspector.getByRole("button", { name: "Pause", exact: true }).click()
    await page.waitForTimeout(150)
    const frames = await canvas.evaluate((element: HTMLCanvasElement) => element.__gnFacilitySnapshot!().frames)
    await page.waitForTimeout(250)
    expect(await canvas.evaluate((element: HTMLCanvasElement) => element.__gnFacilitySnapshot!().frames)).toBe(frames)
    await inspector.getByLabel("Display options", { exact: true }).focus()
    await page.keyboard.press("Enter")
    await expect(inspector.getByRole("button", { name: "Use still image", exact: true })).toBeVisible()
    await inspector.getByRole("checkbox", { name: "Equipment motion" }).focus()
    await page.keyboard.press("Escape")
    await expect(inspector.getByLabel("Display options", { exact: true })).toBeFocused()
    await expect(inspector.getByRole("button", { name: "Use still image", exact: true })).toBeHidden()
    await expect(inspector.getByRole("button", { name: "Workloads", exact: true })).toHaveAttribute("aria-pressed", "true")
    await chooseFacilityStillImage(inspector)
    await expect(page.locator("canvas")).toHaveCount(0)
    await expect(inspector.getByRole("button", { name: "Explore in 3D" })).toBeFocused()
    await page.waitForTimeout(1_600)
    await expect(inspector).toHaveAttribute("data-phase", "poster")
  })

  test("normal production rendering exposes no diagnostic snapshot or per-frame DOM mutations", async ({ page }) => {
    await page.goto("/")
    const inspector = page.getByTestId("facility-inspection")
    await scrollFacilityIntoView(inspector)
    await expect(inspector).toHaveAttribute("data-phase", "ready")
    const diagnostics = await inspector.locator("canvas").evaluate(async (element: HTMLCanvasElement) => {
      let mutations = 0
      const observer = new MutationObserver(records => { mutations += records.length })
      observer.observe(element, { attributes: true })
      await new Promise(resolve => setTimeout(resolve, 350))
      observer.disconnect()
      return { hook: typeof element.__gnFacilitySnapshot, framesAttribute: element.hasAttribute("data-frames"), mutations }
    })
    expect(diagnostics).toEqual({ hook: "undefined", framesAttribute: false, mutations: 0 })
  })

  test("reduced motion, fixture D, keyboard selection and reset retain authoritative records", async ({ page }) => {
    await page.emulateMedia({ reducedMotion: "reduce" })
    await page.goto("/demo?scenario=d&perspective=engineering")
    const inspector = page.getByTestId("facility-inspection")
    await scrollFacilityIntoView(inspector)
    await expect(inspector).toHaveAttribute("data-phase", "ready")
    await inspector.locator(".facility-settings summary").click()
    await expect(inspector.getByRole("checkbox", { name: "Equipment motion" })).toBeDisabled()
    await expect(inspector.getByRole("button", { name: "Pause", exact: true })).toHaveCount(0)
    await inspector.locator(".facility-systems").getByRole("button", { name: "Cooling", exact: true }).focus()
    await page.keyboard.press("Enter")
    await expect(inspector).toContainText("missing")
    await expect(page.getByTestId("assessment-summary")).toContainText("Unknown")
    if (await inspector.getAttribute("data-night-inspection")) {
      await inspector.getByTestId("facility-contextual-inspector").locator("summary").filter({ hasText: /^Evidence$/ }).click()
      await expect(inspector.getByRole("link", { name: "Read this versioned decision brief" })).toHaveAttribute("href", /demo-01-d\/v1.0.0/)
    } else await expect(inspector.getByRole("link", { name: /published decision brief/ })).toHaveAttribute("href", /demo-01-d\/v1.0.0/)
    await page.getByRole("button", { name: "Reset example" }).click()
    await expect(inspector).toHaveAttribute("data-scenario", "b")
    await expect(inspector.locator('.facility-systems [aria-pressed="true"]')).toHaveCount(0)
    const scan = await new AxeBuilder({ page }).include('[data-testid="facility-inspection"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()
    expect(scan.violations).toEqual([])
  })

  test("failed transfer restores poster, requires explicit retry and closes stale loads", async ({ page }) => {
    await page.emulateMedia({ reducedMotion: "reduce" })
    await page.addInitScript(() => Object.defineProperty(navigator, "connection", { configurable: true, value: { saveData: true, effectiveType: "4g" } }))
    await page.route("**/facility.glb", route => route.abort())
    await page.goto("/")
    const inspector = page.getByTestId("facility-inspection")
    await scrollFacilityIntoView(inspector)
    await inspector.getByRole("button", { name: "Explore in 3D" }).click()
    await expect(inspector).toHaveAttribute("data-phase", "failed")
    await expect(inspector.locator(".facility-poster")).toBeVisible()
    await expect(inspector).toContainText("7.0 MW")
    await page.unroute("**/facility.glb")
    await inspector.getByRole("button", { name: "Retry 3D" }).click()
    await expect(inspector).toHaveAttribute("data-phase", "ready")
    await chooseFacilityStillImage(inspector)
    await page.route("**/facility.glb", async route => { await new Promise(resolve => setTimeout(resolve, 1_000)); await route.continue().catch(() => {}) })
    await inspector.getByRole("button", { name: "Explore in 3D" }).click()
    await chooseFacilityStillImage(inspector)
    await page.waitForTimeout(1_200)
    await expect(inspector).toHaveAttribute("data-phase", "poster")
    await expect(inspector.locator("canvas")).toHaveCount(0)
  })

  test("Save-Data blocks automatic downloads while manual activation works", async ({ page }) => {
    await page.addInitScript(() => Object.defineProperty(navigator, "connection", { configurable: true, value: { saveData: true, effectiveType: "4g" } }))
    const models: string[] = []
    page.on("request", request => { if (request.url().endsWith("facility.glb")) models.push(request.url()) })
    await page.goto("/")
    const inspector = page.getByTestId("facility-inspection")
    await scrollFacilityIntoView(inspector)
    await page.waitForTimeout(1_700)
    expect(models).toEqual([])
    await inspector.getByRole("button", { name: "Explore in 3D" }).click()
    await expect(inspector).toHaveAttribute("data-phase", "ready")
    expect(models).toHaveLength(1)
  })
})
