import type { Metadata } from "next"
import Link from "next/link"
import { ContactForm } from "@/components/forms/contact-form"
import { SectionShell } from "@/components/layout/section-shell"
import { AssessmentCards } from "@/components/marketing/assessment-cards"
import { Hero } from "@/components/marketing/hero"
import { SectionHeader } from "@/components/marketing/section-header"
import { SeoPageJsonLd } from "@/components/seo/json-ld"
import { RelatedSeoLinks } from "@/components/seo/related-seo-links"
import { assessmentDeliverables, assessmentInputs, assessmentSteps, assessmentOutcomes } from "@/content/copy/assessment"
import { createPageMetadata } from "@/lib/seo"
export async function generateMetadata(): Promise<Metadata> { return createPageMetadata({ path: "/assessment" }) }
export default function AssessmentPage() { return <div className="space-y-16 pb-16"><SeoPageJsonLd path="/assessment" /><Hero eyebrow="A bounded, paid assessment" headline="Scope your next capacity decision." body="Evaluate one capacity question using authorized historical inputs. Agree the facility boundary, workload profiles, conditions, and review criteria before analysis begins." primaryCta={{label:"Scope an assessment",href:"#scope"}} secondaryCta={{label:"See a sample decision brief",href:"/demo#decision-brief"}} trustLine="Scoping is a conversation. Work begins only under an agreed paid scope." />
<SectionShell id="deliverables" deferRendering={false}><div className="space-y-8"><SectionHeader eyebrow="What you receive" headline="A decision brief with a traceable basis." body="The engagement defines one decision, a facility boundary, a historical window, agreed alternatives, reviewers, deliverables, and review rounds. Inputs and conclusions remain scoped to that agreement." /><AssessmentCards items={assessmentDeliverables} /></div></SectionShell>
<SectionShell deferRendering={false}><div className="space-y-8"><SectionHeader eyebrow="Before modeling" headline="Confirm readiness, permissions, and responsibilities." body="The site or data owner must authorize the historical inputs and confirm the relevant operating context. A useful assessment depends on that evidence being available and interpretable." /><AssessmentCards items={assessmentInputs} /><p className="text-base leading-8 text-muted-foreground">Do not submit telemetry, facility diagrams, credentials, or commercially sensitive files through this website. Any operational-data exchange is agreed separately. <Link className="text-primary underline underline-offset-4" href="/data-handling">Review data handling.</Link></p></div></SectionShell>
<SectionShell deferRendering={false}><div className="space-y-8"><SectionHeader eyebrow="How it starts" headline="Fit, readiness, then a paid scope." body="Schedule and price depend on the question, evidence, and agreed work. No fixed delivery period or performance improvement is promised here." /><AssessmentCards items={assessmentSteps} /></div></SectionShell>
<SectionShell deferRendering={false}><div className="space-y-8"><SectionHeader eyebrow="Decision value" headline="A useful answer need not be a larger number." body="Report acceptance, commercial usefulness, modeled eligibility, and operating authorization are separate decisions." /><AssessmentCards items={assessmentOutcomes} /><details className="gn-panel p-6"><summary className="cursor-pointer text-lg font-medium">Boundaries and change control</summary><p className="mt-4 text-base leading-8 text-muted-foreground">The assessment does not grant equipment control, guarantee safe sellable MW, certify facility safety, or replace engineering and operator approval. Live connectivity, operational-file ingestion, investment recommendations, recurring services, and autonomous control require separate evaluation and agreement. New facilities, time windows, profiles, or review rounds are scope changes to agree before additional work.</p></details></div></SectionShell>
<SectionShell id="scope" deferRendering={false}><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeader eyebrow="Start the conversation" headline="Which commitment are you evaluating?" body="Share your organization and contact details. A short description of the decision is helpful but optional. This inquiry does not buy an assessment or authorize operational work." /><ContactForm source="assessment-page" /></div></SectionShell><RelatedSeoLinks path="/assessment" /></div> }
