import { AssessmentAttribution } from "@/components/assessment/assessment-attribution"
import { AssessmentCapacityTable } from "@/components/assessment/assessment-capacity-table"
import type { AssessmentPerspective, AssessmentRecord } from "@/types/assessment"

export function AssessmentDetails({ record, perspective = "business" }: { record: AssessmentRecord; perspective?: AssessmentPerspective }) {
  return <div className="space-y-8">
    <div className="grid gap-7 md:grid-cols-2"><section><h3 className="text-xl font-medium">Governing conditions</h3><ul className="mt-4 space-y-3 text-muted-foreground">{record.reasons.map((reason) => <li key={reason.id} className="leading-7"><strong className="font-medium text-foreground">{reason.label}. </strong>{reason.detail}</li>)}</ul></section><section><h3 className="text-xl font-medium">Commercial and operational status</h3><p className="mt-4 leading-7 text-muted-foreground">Economics unestimated. {record.economics.reason}</p><p className="mt-3 leading-7 text-muted-foreground">Report acceptance: not applicable. {record.reportAcceptance.reason}</p><p className="mt-3 leading-7 text-muted-foreground">No operational authority. Model screening is separate from permission to operate, operator acceptance, and delivered capacity.</p></section></div>
    <section><h3 className="text-xl font-medium">What this example assumes</h3><ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-muted-foreground">{record.assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul></section>
    {perspective === "engineering" && <><AssessmentCapacityTable record={record} /><AssessmentAttribution record={record} /><section><h3 className="text-xl font-medium">Evidence register</h3><dl className="mt-4 grid gap-4 md:grid-cols-3">{record.evidence.map((item) => <div key={item.id} className="rounded-xl border border-border p-4"><dt className="font-medium">{item.label} · {item.status}</dt><dd className="mt-2 text-sm leading-6 text-muted-foreground">{item.detail}</dd></div>)}</dl><p className="mt-4 break-words text-sm leading-6 text-muted-foreground">Dataset: {record.datasetId}. Model: {record.modelVersion}. Schema: {record.schemaVersion}.</p></section></>}
    <details className="rounded-xl border border-border p-5"><summary className="cursor-pointer font-medium">Options to investigate · all unassessed</summary><p className="mt-4 leading-7 text-muted-foreground">These are questions for a scoped assessment. No ranking, feasibility, cost, benefit, or recommendation has been established.</p><ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground">{record.investigationOptions.map((option) => <li key={option.id}>{option.label} — {option.status}</li>)}</ul></details>
    <section><h3 className="text-xl font-medium">Limits of this evidence</h3><ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-muted-foreground">{record.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></section>
  </div>
}
